using System;
using System.Collections.Generic;
using UnityEditor;

namespace BattleTurn.AudioManager.Editor
{
    internal static class Util
    {
        internal const string GENERATED_FOLDER_PATH = "Assets/Plugins/BattleTurn/Generated/AudioManager";
        internal const string GENERATED_RUNTIME_NAMESPACE = nameof(BattleTurn) + "." + nameof(AudioManager) + "." + nameof(Runtime);

        internal const string AUTO_GENERATED_MARKER = "// <auto-generated/>";
        internal const string DO_NOT_MODIFY_MARKER = "// Do not modify by hand";

        internal static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
        {
            "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const","continue",
            "decimal","default","delegate","do","double","else","enum","event","explicit","extern","false","finally","fixed",
            "float","for","foreach","goto","if","implicit","in","int","interface","internal","is","lock","long","namespace",
            "new","null","object","operator","out","override","params","private","protected","public","readonly","ref","return",
            "sbyte","sealed","short","sizeof","stackalloc","static","string","struct","switch","this","throw","true","try",
            "typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while"
        };

        internal static void EnsureFolderExists(string unityFolderPath)
        {
            if (AssetDatabase.IsValidFolder(unityFolderPath))
                return;

            var parts = unityFolderPath.Split('/');
            var current = parts[0];
            for (var i = 1; i < parts.Length; i++)
            {
                var next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                    AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }
        }
    }
}