using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using BattleTurn.AudioManager.Runtime;
using UnityEditor;
using UnityEngine;

namespace BattleTurn.AudioManager.Editor
{
    internal static class AudioNameEnumGenerator
    {
        private const string GeneratedFolderUnityPath = "Assets/Plugins/BattleTurn/Generated/AudioManager";
        private const string GeneratedFileName = "AudioName.cs";
        private const string EnumNamespace = "BattleTurn.AudioManager.Runtime";
        private const string EnumName = "AudioName";

        private const string AutoGeneratedMarker = "// <auto-generated/>";
        private const string DoNotModifyMarker = "Do not modify by hand";

        private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
        {
            "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const","continue",
            "decimal","default","delegate","do","double","else","enum","event","explicit","extern","false","finally","fixed",
            "float","for","foreach","goto","if","implicit","in","int","interface","internal","is","lock","long","namespace",
            "new","null","object","operator","out","override","params","private","protected","public","readonly","ref","return",
            "sbyte","sealed","short","sizeof","stackalloc","static","string","struct","switch","this","throw","true","try",
            "typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while"
        };

        public static bool BuildFromAllAudioDataAssets(bool force)
        {
            var rawNames = new List<string>();

            // NOTE: FindAssets without folders can be non-deterministic; we also scope to common roots.
            var guids = AssetDatabase.FindAssets("t:AudioData", new[] { "Assets", "Packages" });
            if (force && (guids == null || guids.Length == 0))
                Debug.LogWarning("AudioNameEnumGenerator: No AudioData assets found. Create an AudioData asset in the Project window (Assets) then press Build again.");

            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var audioData = AssetDatabase.LoadAssetAtPath<AudioData>(path);
                if (audioData == null)
                    continue;

                if (audioData.audioContents == null)
                    continue;

                foreach (var content in audioData.audioContents)
                {
                    if (content == null)
                        continue;

                    rawNames.Add(content.name);
                }
            }

            if (force && rawNames.Count == 0)
                Debug.LogWarning("AudioNameEnumGenerator: Found AudioData assets but no AudioContent names were collected (empty list or empty names). Enum will contain only None.");

            return BuildFromNames(rawNames, force);
        }

        public static bool BuildFromAudioData(AudioData audioData, bool force)
        {
            if (audioData == null)
                return BuildFromNames(Array.Empty<string>(), force);

            var rawNames = new List<string>();
            if (audioData.audioContents != null)
            {
                foreach (var content in audioData.audioContents)
                {
                    if (content == null)
                        continue;

                    rawNames.Add(content.name);
                }
            }

            return BuildFromNames(rawNames, force);
        }

        private static bool BuildFromNames(IReadOnlyList<string> rawNames, bool force)
        {
            var canonicalUnityPath = GetGeneratedFileAssetPath();

            // If the user moved the generated enum, remove the moved/duplicate copy and regenerate at the canonical path.
            var didDelete = DeleteRelocatedOrDuplicateGeneratedFiles(canonicalUnityPath);

            var enumMembers = MakeEnumMembers(rawNames);
            var newSource = GenerateSource(enumMembers);

            var fileAssetPath = canonicalUnityPath;
            var fileAbsolutePath = GetAbsolutePathFromUnityPath(fileAssetPath);

            if (File.Exists(fileAbsolutePath))
            {
                var oldSource = File.ReadAllText(fileAbsolutePath);
                var unchanged = string.Equals(oldSource, newSource, StringComparison.Ordinal);
                if (!force && unchanged && !didDelete)
                    return false;

                // Avoid touching the file when unchanged; domain reload loops are often triggered by rewriting the same content.
                if (unchanged && !force)
                    return false;
            }
            else
            {
                // Ensure folder exists for first-time generation.
                EnsureFolderExists(GeneratedFolderUnityPath);
            }

            EnsureFolderExists(GeneratedFolderUnityPath);
            File.WriteAllText(fileAbsolutePath, newSource, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

            AssetDatabase.ImportAsset(fileAssetPath, ImportAssetOptions.ForceUpdate);
            return true;
        }

        private static List<string> MakeEnumMembers(IReadOnlyList<string> rawNames)
        {
            // Deterministic output to avoid rewrite/recompile loops.
            // Strategy: sanitize -> group counts -> output sorted keys -> suffix duplicates with _2, _3...
            if (rawNames == null || rawNames.Count == 0)
                return new List<string>();

            var sanitized = rawNames
                .Select(SanitizeToIdentifier)
                .Where(s => !string.IsNullOrEmpty(s))
                .ToList();

            var counts = new Dictionary<string, int>(StringComparer.Ordinal);
            foreach (var s in sanitized)
            {
                if (counts.TryGetValue(s, out var c))
                    counts[s] = c + 1;
                else
                    counts[s] = 1;
            }

            var result = new List<string>();
            foreach (var key in counts.Keys.OrderBy(k => k, StringComparer.Ordinal))
            {
                if (string.Equals(key, "None", StringComparison.Ordinal))
                {
                    // Reserve None for the explicit enum member.
                    var n = counts[key];
                    for (var i = 1; i <= n; i++)
                        result.Add(i == 1 ? "None_1" : $"None_{i}");
                    continue;
                }

                var nKey = counts[key];
                if (nKey == 1)
                {
                    result.Add(key);
                }
                else
                {
                    result.Add(key);
                    for (var i = 2; i <= nKey; i++)
                        result.Add($"{key}_{i}");
                }
            }

            return result;
        }

        private static string SanitizeToIdentifier(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw))
                return string.Empty;

            var trimmed = raw.Trim();

            var sb = new StringBuilder(trimmed.Length);
            foreach (var ch in trimmed)
            {
                sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            }

            var id = Regex.Replace(sb.ToString(), "_+", "_");
            id = id.Trim('_');

            if (string.IsNullOrEmpty(id))
                return string.Empty;

            if (char.IsDigit(id[0]))
                id = "_" + id;

            if (CSharpKeywords.Contains(id))
                id = "_" + id;

            return id;
        }

        private static string GenerateSource(IReadOnlyList<string> members)
        {
            var sb = new StringBuilder(512);
            sb.AppendLine("// <auto-generated/> Do not modify by hand or move.");
            sb.AppendLine("#pragma warning disable 1591");
            sb.Append("namespace ").Append(EnumNamespace).AppendLine();
            sb.AppendLine("{");
            sb.Append("    public enum ").Append(EnumName).AppendLine();
            sb.AppendLine("    {");
            sb.AppendLine("        None = 0,");

            if (members != null)
            {
                var value = 1;
                foreach (var member in members)
                {
                    sb.Append("        ").Append(member).Append(" = ").Append(value).AppendLine(",");
                    value++;
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static bool DeleteRelocatedOrDuplicateGeneratedFiles(string canonicalUnityPath)
        {
            var didDelete = false;

            // Clean up any moved copies under Assets/ (searched via AssetDatabase)
            var guids = AssetDatabase.FindAssets("AudioName t:MonoScript");
            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                if (!path.EndsWith("/" + GeneratedFileName, StringComparison.Ordinal))
                    continue;

                if (string.Equals(path, canonicalUnityPath, StringComparison.Ordinal))
                    continue;

                // Only delete files that look like our generated output to avoid nuking user scripts.
                if (IsGeneratedAudioNameFile(path))
                {
                    didDelete |= AssetDatabase.DeleteAsset(path);
                }
            }

            // Clean up any legacy location in Packages/ that we previously created.
            var legacyPackagePath = "Packages/AudioManager/Runtime/AudioName.cs";
            if (!string.Equals(legacyPackagePath, canonicalUnityPath, StringComparison.Ordinal) &&
                File.Exists(GetAbsolutePathFromUnityPath(legacyPackagePath)) &&
                IsGeneratedAudioNameFile(legacyPackagePath))
            {
                didDelete |= AssetDatabase.DeleteAsset(legacyPackagePath);
            }

            return didDelete;
        }

        private static bool IsGeneratedAudioNameFile(string unityPath)
        {
            try
            {
                var absolutePath = GetAbsolutePathFromUnityPath(unityPath);
                if (!File.Exists(absolutePath))
                    return false;

                var text = File.ReadAllText(absolutePath);
                return text.Contains(AutoGeneratedMarker, StringComparison.Ordinal) &&
                       text.Contains(DoNotModifyMarker, StringComparison.Ordinal) &&
                       text.Contains("enum AudioName", StringComparison.Ordinal);
            }
            catch
            {
                return false;
            }
        }

        private static string GetGeneratedFileAssetPath()
        {
            return $"{GeneratedFolderUnityPath}/{GeneratedFileName}";
        }

        private static void EnsureFolderExists(string folderUnityPath)
        {
            var folderAbsolutePath = GetAbsolutePathFromUnityPath(folderUnityPath);
            Directory.CreateDirectory(folderAbsolutePath);
        }

        private static string GetAbsolutePathFromUnityPath(string unityPath)
        {
            if (string.IsNullOrEmpty(unityPath))
                throw new ArgumentException("unityPath is null or empty", nameof(unityPath));

            var projectRoot = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));

            if (unityPath == "Assets")
                return Application.dataPath;

            if (unityPath.StartsWith("Assets/", StringComparison.Ordinal))
            {
                var relative = unityPath.Substring("Assets/".Length);
                return Path.Combine(Application.dataPath, relative);
            }

            if (unityPath.StartsWith("Packages/", StringComparison.Ordinal))
                return Path.Combine(projectRoot, unityPath);

            throw new ArgumentException($"Expected a Unity path starting with 'Assets/' or 'Packages/' but got '{unityPath}'", nameof(unityPath));
        }
    }
}
