using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
using UnityEngine.Audio;

namespace BattleTurn.AudioManager.Editor
{
    internal static class AudioMixerGroupNameGenerator
    {
        private const string GeneratedFolderUnityPath = "Assets/Plugins/BattleTurn/Generated/AudioManager";
        private const string GameMixerUnityPath = GeneratedFolderUnityPath + "/GameMixer.mixer";
        private const string GeneratedFileUnityPath = GeneratedFolderUnityPath + "/AudioMixerGroupName.cs";

        private const string GeneratedNamespace = "BattleTurn.AudioManager.Runtime";
        private const string GeneratedClassName = "AudioMixerGroupName";

        private const string AutoGeneratedMarker = "// <auto-generated/>";
        private const string DoNotModifyMarker = "// Do not modify by hand";

        public static bool EnsureGeneratedIfMissing()
        {
            var absolutePath = GetAbsolutePathFromUnityPath(GeneratedFileUnityPath);
            if (File.Exists(absolutePath))
                return false;

            return BuildFromGameMixer(force: true);
        }

        public static bool BuildFromGameMixer(bool force)
        {
            var mixer = AssetDatabase.LoadAssetAtPath<AudioMixer>(GameMixerUnityPath);
            if (mixer == null)
                return false;

            return BuildFromMixer(mixer, force);
        }

        public static bool BuildFromMixerPath(string mixerUnityPath, bool force)
        {
            if (string.IsNullOrWhiteSpace(mixerUnityPath))
                return false;

            var mixer = AssetDatabase.LoadAssetAtPath<AudioMixer>(mixerUnityPath);
            if (mixer == null)
                return false;

            return BuildFromMixer(mixer, force);
        }

        public static bool BuildFromMixer(AudioMixer mixer, bool force)
        {
            if (mixer == null)
                return false;

            Util.EnsureFolderExists(GeneratedFolderUnityPath);

            var names = (mixer.FindMatchingGroups(string.Empty) ?? Array.Empty<AudioMixerGroup>())
                .Where(g => g != null)
                .Select(g => g.name)
                .Where(n => !string.IsNullOrWhiteSpace(n))
                .Distinct(StringComparer.Ordinal)
                .OrderBy(n => n, StringComparer.Ordinal)
                .ToList();

            var source = GenerateSource(names);

            var absolutePath = GetAbsolutePathFromUnityPath(GeneratedFileUnityPath);
            if (File.Exists(absolutePath))
            {
                var old = File.ReadAllText(absolutePath);
                var unchanged = string.Equals(old, source, StringComparison.Ordinal);
                if (unchanged)
                    return false;
            }

            File.WriteAllText(absolutePath, source, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            AssetDatabase.ImportAsset(GeneratedFileUnityPath, ImportAssetOptions.ForceUpdate);
            return true;
        }

        private static string GenerateSource(IReadOnlyList<string> groupNames)
        {
            var sb = new StringBuilder(1024);
            sb.AppendLine(AutoGeneratedMarker);
            sb.AppendLine(DoNotModifyMarker);
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {GeneratedClassName}");
            sb.AppendLine("    {");

            var used = new HashSet<string>(StringComparer.Ordinal);
            foreach (var groupName in groupNames)
            {
                var constName = MakeIdentifier(groupName);
                constName = MakeUnique(constName, used);
                used.Add(constName);

                sb.AppendLine($"        public const string {constName} = \"{Escape(groupName)}\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            return sb.ToString();
        }

        private static string Escape(string s)
        {
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string MakeIdentifier(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw))
                return "EMPTY";

            var cleaned = Regex.Replace(raw.Trim(), "[^a-zA-Z0-9]+", "_");
            cleaned = Regex.Replace(cleaned, "_{2,}", "_").Trim('_');
            if (string.IsNullOrEmpty(cleaned))
                cleaned = "GROUP";

            cleaned = cleaned.ToUpperInvariant();

            if (char.IsDigit(cleaned[0]))
                cleaned = "_" + cleaned;

            if (IsCSharpKeyword(cleaned))
                cleaned += "_";

            return cleaned;
        }

        private static bool IsCSharpKeyword(string s)
        {
            return s.ToLowerInvariant() is "class" or "namespace" or "public" or "private" or "protected" or "internal" or "static" or "string" or "const";
        }

        private static string MakeUnique(string name, HashSet<string> used)
        {
            if (!used.Contains(name))
                return name;

            var i = 2;
            while (used.Contains(name + "_" + i))
                i++;

            return name + "_" + i;
        }

        private static string GetAbsolutePathFromUnityPath(string unityPath)
        {
            if (unityPath.StartsWith("Assets/", StringComparison.Ordinal))
            {
                var rel = unityPath.Substring("Assets/".Length);
                return Path.Combine(Application.dataPath, rel);
            }

            throw new ArgumentException($"Expected Assets-relative path but got '{unityPath}'", nameof(unityPath));
        }
    }
}
